/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Concepts implements Serializable {

    private static final long serialVersionUID = -1903526435;

    private Integer       id;
    private String        system;
    private String        version;
    private String        term;
    private String        text;
    private Integer       sourceId;
    private Integer       createdBy;
    private LocalDateTime createdAt;

    public Concepts() {}

    public Concepts(Concepts value) {
        this.id = value.id;
        this.system = value.system;
        this.version = value.version;
        this.term = value.term;
        this.text = value.text;
        this.sourceId = value.sourceId;
        this.createdBy = value.createdBy;
        this.createdAt = value.createdAt;
    }

    public Concepts(
        Integer       id,
        String        system,
        String        version,
        String        term,
        String        text,
        Integer       sourceId,
        Integer       createdBy,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.system = system;
        this.version = version;
        this.term = term;
        this.text = text;
        this.sourceId = sourceId;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSystem() {
        return this.system;
    }

    public void setSystem(String system) {
        this.system = system;
    }

    public String getVersion() {
        return this.version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getTerm() {
        return this.term;
    }

    public void setTerm(String term) {
        this.term = term;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Integer getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Concepts (");

        sb.append(id);
        sb.append(", ").append(system);
        sb.append(", ").append(version);
        sb.append(", ").append(term);
        sb.append(", ").append(text);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
