/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.pojos;


import de.mig.mdr.dal.jooq.enums.RelationType;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConceptElementAssociations implements Serializable {

    private static final long serialVersionUID = -1138524444;

    private Integer       conceptId;
    private Integer       scopedidentifierId;
    private RelationType  linktype;
    private Integer       createdBy;
    private LocalDateTime createdAt;

    public ConceptElementAssociations() {}

    public ConceptElementAssociations(ConceptElementAssociations value) {
        this.conceptId = value.conceptId;
        this.scopedidentifierId = value.scopedidentifierId;
        this.linktype = value.linktype;
        this.createdBy = value.createdBy;
        this.createdAt = value.createdAt;
    }

    public ConceptElementAssociations(
        Integer       conceptId,
        Integer       scopedidentifierId,
        RelationType  linktype,
        Integer       createdBy,
        LocalDateTime createdAt
    ) {
        this.conceptId = conceptId;
        this.scopedidentifierId = scopedidentifierId;
        this.linktype = linktype;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
    }

    public Integer getConceptId() {
        return this.conceptId;
    }

    public void setConceptId(Integer conceptId) {
        this.conceptId = conceptId;
    }

    public Integer getScopedidentifierId() {
        return this.scopedidentifierId;
    }

    public void setScopedidentifierId(Integer scopedidentifierId) {
        this.scopedidentifierId = scopedidentifierId;
    }

    public RelationType getLinktype() {
        return this.linktype;
    }

    public void setLinktype(RelationType linktype) {
        this.linktype = linktype;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ConceptElementAssociations (");

        sb.append(conceptId);
        sb.append(", ").append(scopedidentifierId);
        sb.append(", ").append(linktype);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
