/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetSlotByUrn implements Serializable {

    private static final long serialVersionUID = 1076274080;

    private Integer id;
    private Integer scopedIdentifierId;
    private String  key;
    private String  value;

    public GetSlotByUrn() {}

    public GetSlotByUrn(GetSlotByUrn value) {
        this.id = value.id;
        this.scopedIdentifierId = value.scopedIdentifierId;
        this.key = value.key;
        this.value = value.value;
    }

    public GetSlotByUrn(
        Integer id,
        Integer scopedIdentifierId,
        String  key,
        String  value
    ) {
        this.id = id;
        this.scopedIdentifierId = scopedIdentifierId;
        this.key = key;
        this.value = value;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getScopedIdentifierId() {
        return this.scopedIdentifierId;
    }

    public void setScopedIdentifierId(Integer scopedIdentifierId) {
        this.scopedIdentifierId = scopedIdentifierId;
    }

    public String getKey() {
        return this.key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GetSlotByUrn (");

        sb.append(id);
        sb.append(", ").append(scopedIdentifierId);
        sb.append(", ").append(key);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
