/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissibleCode implements Serializable {

    private static final long serialVersionUID = -1938489905;

    private Integer codeScopedIdentifierId;
    private Integer catalogValueDomainId;

    public PermissibleCode() {}

    public PermissibleCode(PermissibleCode value) {
        this.codeScopedIdentifierId = value.codeScopedIdentifierId;
        this.catalogValueDomainId = value.catalogValueDomainId;
    }

    public PermissibleCode(
        Integer codeScopedIdentifierId,
        Integer catalogValueDomainId
    ) {
        this.codeScopedIdentifierId = codeScopedIdentifierId;
        this.catalogValueDomainId = catalogValueDomainId;
    }

    public Integer getCodeScopedIdentifierId() {
        return this.codeScopedIdentifierId;
    }

    public void setCodeScopedIdentifierId(Integer codeScopedIdentifierId) {
        this.codeScopedIdentifierId = codeScopedIdentifierId;
    }

    public Integer getCatalogValueDomainId() {
        return this.catalogValueDomainId;
    }

    public void setCatalogValueDomainId(Integer catalogValueDomainId) {
        this.catalogValueDomainId = catalogValueDomainId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PermissibleCode (");

        sb.append(codeScopedIdentifierId);
        sb.append(", ").append(catalogValueDomainId);

        sb.append(")");
        return sb.toString();
    }
}
