/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.pojos;


import de.mig.mdr.dal.jooq.enums.RelationType;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScopedIdentifierRelation implements Serializable {

    private static final long serialVersionUID = -669159712;

    private Integer       leftIdentifierId;
    private Integer       rightIdentifierId;
    private RelationType  relation;
    private Integer       createdBy;
    private LocalDateTime createdAt;

    public ScopedIdentifierRelation() {}

    public ScopedIdentifierRelation(ScopedIdentifierRelation value) {
        this.leftIdentifierId = value.leftIdentifierId;
        this.rightIdentifierId = value.rightIdentifierId;
        this.relation = value.relation;
        this.createdBy = value.createdBy;
        this.createdAt = value.createdAt;
    }

    public ScopedIdentifierRelation(
        Integer       leftIdentifierId,
        Integer       rightIdentifierId,
        RelationType  relation,
        Integer       createdBy,
        LocalDateTime createdAt
    ) {
        this.leftIdentifierId = leftIdentifierId;
        this.rightIdentifierId = rightIdentifierId;
        this.relation = relation;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
    }

    public Integer getLeftIdentifierId() {
        return this.leftIdentifierId;
    }

    public void setLeftIdentifierId(Integer leftIdentifierId) {
        this.leftIdentifierId = leftIdentifierId;
    }

    public Integer getRightIdentifierId() {
        return this.rightIdentifierId;
    }

    public void setRightIdentifierId(Integer rightIdentifierId) {
        this.rightIdentifierId = rightIdentifierId;
    }

    public RelationType getRelation() {
        return this.relation;
    }

    public void setRelation(RelationType relation) {
        this.relation = relation;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ScopedIdentifierRelation (");

        sb.append(leftIdentifierId);
        sb.append(", ").append(rightIdentifierId);
        sb.append(", ").append(relation);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
