/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScopedIdentifierHierarchy implements Serializable {

    private static final long serialVersionUID = -816811154;

    private Integer superId;
    private Integer subId;
    private Integer order;

    public ScopedIdentifierHierarchy() {}

    public ScopedIdentifierHierarchy(ScopedIdentifierHierarchy value) {
        this.superId = value.superId;
        this.subId = value.subId;
        this.order = value.order;
    }

    public ScopedIdentifierHierarchy(
        Integer superId,
        Integer subId,
        Integer order
    ) {
        this.superId = superId;
        this.subId = subId;
        this.order = order;
    }

    public Integer getSuperId() {
        return this.superId;
    }

    public void setSuperId(Integer superId) {
        this.superId = superId;
    }

    public Integer getSubId() {
        return this.subId;
    }

    public void setSubId(Integer subId) {
        this.subId = subId;
    }

    public Integer getOrder() {
        return this.order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ScopedIdentifierHierarchy (");

        sb.append(superId);
        sb.append(", ").append(subId);
        sb.append(", ").append(order);

        sb.append(")");
        return sb.toString();
    }
}
