/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.pojos;


import de.mig.mdr.dal.jooq.enums.ElementType;
import de.mig.mdr.dal.jooq.enums.Status;

import java.io.Serializable;
import java.util.UUID;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScopedIdentifier implements Serializable {

    private static final long serialVersionUID = 1660477940;

    private Integer     id;
    private ElementType elementType;
    private Integer     version;
    private Integer     identifier;
    private String      url;
    private Integer     createdBy;
    private Status      status;
    private Integer     elementId;
    private Integer     namespaceId;
    private UUID        uuid;

    public ScopedIdentifier() {}

    public ScopedIdentifier(ScopedIdentifier value) {
        this.id = value.id;
        this.elementType = value.elementType;
        this.version = value.version;
        this.identifier = value.identifier;
        this.url = value.url;
        this.createdBy = value.createdBy;
        this.status = value.status;
        this.elementId = value.elementId;
        this.namespaceId = value.namespaceId;
        this.uuid = value.uuid;
    }

    public ScopedIdentifier(
        Integer     id,
        ElementType elementType,
        Integer     version,
        Integer     identifier,
        String      url,
        Integer     createdBy,
        Status      status,
        Integer     elementId,
        Integer     namespaceId,
        UUID        uuid
    ) {
        this.id = id;
        this.elementType = elementType;
        this.version = version;
        this.identifier = identifier;
        this.url = url;
        this.createdBy = createdBy;
        this.status = status;
        this.elementId = elementId;
        this.namespaceId = namespaceId;
        this.uuid = uuid;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public ElementType getElementType() {
        return this.elementType;
    }

    public void setElementType(ElementType elementType) {
        this.elementType = elementType;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Integer getIdentifier() {
        return this.identifier;
    }

    public void setIdentifier(Integer identifier) {
        this.identifier = identifier;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public Integer getElementId() {
        return this.elementId;
    }

    public void setElementId(Integer elementId) {
        this.elementId = elementId;
    }

    public Integer getNamespaceId() {
        return this.namespaceId;
    }

    public void setNamespaceId(Integer namespaceId) {
        this.namespaceId = namespaceId;
    }

    public UUID getUuid() {
        return this.uuid;
    }

    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ScopedIdentifier (");

        sb.append(id);
        sb.append(", ").append(elementType);
        sb.append(", ").append(version);
        sb.append(", ").append(identifier);
        sb.append(", ").append(url);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(status);
        sb.append(", ").append(elementId);
        sb.append(", ").append(namespaceId);
        sb.append(", ").append(uuid);

        sb.append(")");
        return sb.toString();
    }
}
