/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Source implements Serializable {

    private static final long serialVersionUID = 1806870287;

    private Integer id;
    private String  name;
    private String  prefix;
    private String  baseUrl;

    public Source() {}

    public Source(Source value) {
        this.id = value.id;
        this.name = value.name;
        this.prefix = value.prefix;
        this.baseUrl = value.baseUrl;
    }

    public Source(
        Integer id,
        String  name,
        String  prefix,
        String  baseUrl
    ) {
        this.id = id;
        this.name = name;
        this.prefix = prefix;
        this.baseUrl = baseUrl;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPrefix() {
        return this.prefix;
    }

    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    public String getBaseUrl() {
        return this.baseUrl;
    }

    public void setBaseUrl(String baseUrl) {
        this.baseUrl = baseUrl;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Source (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(prefix);
        sb.append(", ").append(baseUrl);

        sb.append(")");
        return sb.toString();
    }
}
