/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.pojos;


import de.mig.mdr.dal.jooq.enums.GrantType;

import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserNamespaceGrants implements Serializable {

    private static final long serialVersionUID = -1840260158;

    private Integer   userId;
    private Integer   namespaceId;
    private GrantType grantType;

    public UserNamespaceGrants() {}

    public UserNamespaceGrants(UserNamespaceGrants value) {
        this.userId = value.userId;
        this.namespaceId = value.namespaceId;
        this.grantType = value.grantType;
    }

    public UserNamespaceGrants(
        Integer   userId,
        Integer   namespaceId,
        GrantType grantType
    ) {
        this.userId = userId;
        this.namespaceId = namespaceId;
        this.grantType = grantType;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getNamespaceId() {
        return this.namespaceId;
    }

    public void setNamespaceId(Integer namespaceId) {
        this.namespaceId = namespaceId;
    }

    public GrantType getGrantType() {
        return this.grantType;
    }

    public void setGrantType(GrantType grantType) {
        this.grantType = grantType;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserNamespaceGrants (");

        sb.append(userId);
        sb.append(", ").append(namespaceId);
        sb.append(", ").append(grantType);

        sb.append(")");
        return sb.toString();
    }
}
