/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.daos;


import de.mig.mdr.dal.jooq.enums.RelationType;
import de.mig.mdr.dal.jooq.tables.ConceptElementAssociations;
import de.mig.mdr.dal.jooq.tables.records.ConceptElementAssociationsRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConceptElementAssociationsDao extends DAOImpl<ConceptElementAssociationsRecord, de.mig.mdr.dal.jooq.tables.pojos.ConceptElementAssociations, Record2<Integer, Integer>> {

    /**
     * Create a new ConceptElementAssociationsDao without any configuration
     */
    public ConceptElementAssociationsDao() {
        super(ConceptElementAssociations.CONCEPT_ELEMENT_ASSOCIATIONS, de.mig.mdr.dal.jooq.tables.pojos.ConceptElementAssociations.class);
    }

    /**
     * Create a new ConceptElementAssociationsDao with an attached configuration
     */
    public ConceptElementAssociationsDao(Configuration configuration) {
        super(ConceptElementAssociations.CONCEPT_ELEMENT_ASSOCIATIONS, de.mig.mdr.dal.jooq.tables.pojos.ConceptElementAssociations.class, configuration);
    }

    @Override
    public Record2<Integer, Integer> getId(de.mig.mdr.dal.jooq.tables.pojos.ConceptElementAssociations object) {
        return compositeKeyRecord(object.getConceptId(), object.getScopedidentifierId());
    }

    /**
     * Fetch records that have <code>concept_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ConceptElementAssociations> fetchRangeOfConceptId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ConceptElementAssociations.CONCEPT_ELEMENT_ASSOCIATIONS.CONCEPT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>concept_id IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ConceptElementAssociations> fetchByConceptId(Integer... values) {
        return fetch(ConceptElementAssociations.CONCEPT_ELEMENT_ASSOCIATIONS.CONCEPT_ID, values);
    }

    /**
     * Fetch records that have <code>scopedidentifier_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ConceptElementAssociations> fetchRangeOfScopedidentifierId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ConceptElementAssociations.CONCEPT_ELEMENT_ASSOCIATIONS.SCOPEDIDENTIFIER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>scopedidentifier_id IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ConceptElementAssociations> fetchByScopedidentifierId(Integer... values) {
        return fetch(ConceptElementAssociations.CONCEPT_ELEMENT_ASSOCIATIONS.SCOPEDIDENTIFIER_ID, values);
    }

    /**
     * Fetch records that have <code>linktype BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ConceptElementAssociations> fetchRangeOfLinktype(RelationType lowerInclusive, RelationType upperInclusive) {
        return fetchRange(ConceptElementAssociations.CONCEPT_ELEMENT_ASSOCIATIONS.LINKTYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>linktype IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ConceptElementAssociations> fetchByLinktype(RelationType... values) {
        return fetch(ConceptElementAssociations.CONCEPT_ELEMENT_ASSOCIATIONS.LINKTYPE, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ConceptElementAssociations> fetchRangeOfCreatedBy(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ConceptElementAssociations.CONCEPT_ELEMENT_ASSOCIATIONS.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ConceptElementAssociations> fetchByCreatedBy(Integer... values) {
        return fetch(ConceptElementAssociations.CONCEPT_ELEMENT_ASSOCIATIONS.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ConceptElementAssociations> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ConceptElementAssociations.CONCEPT_ELEMENT_ASSOCIATIONS.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ConceptElementAssociations> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(ConceptElementAssociations.CONCEPT_ELEMENT_ASSOCIATIONS.CREATED_AT, values);
    }
}
