/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.daos;


import de.mig.mdr.dal.jooq.enums.RelationType;
import de.mig.mdr.dal.jooq.tables.ScopedIdentifierRelation;
import de.mig.mdr.dal.jooq.tables.records.ScopedIdentifierRelationRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScopedIdentifierRelationDao extends DAOImpl<ScopedIdentifierRelationRecord, de.mig.mdr.dal.jooq.tables.pojos.ScopedIdentifierRelation, Record2<Integer, Integer>> {

    /**
     * Create a new ScopedIdentifierRelationDao without any configuration
     */
    public ScopedIdentifierRelationDao() {
        super(ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION, de.mig.mdr.dal.jooq.tables.pojos.ScopedIdentifierRelation.class);
    }

    /**
     * Create a new ScopedIdentifierRelationDao with an attached configuration
     */
    public ScopedIdentifierRelationDao(Configuration configuration) {
        super(ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION, de.mig.mdr.dal.jooq.tables.pojos.ScopedIdentifierRelation.class, configuration);
    }

    @Override
    public Record2<Integer, Integer> getId(de.mig.mdr.dal.jooq.tables.pojos.ScopedIdentifierRelation object) {
        return compositeKeyRecord(object.getLeftIdentifierId(), object.getRightIdentifierId());
    }

    /**
     * Fetch records that have <code>left_identifier_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ScopedIdentifierRelation> fetchRangeOfLeftIdentifierId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION.LEFT_IDENTIFIER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>left_identifier_id IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ScopedIdentifierRelation> fetchByLeftIdentifierId(Integer... values) {
        return fetch(ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION.LEFT_IDENTIFIER_ID, values);
    }

    /**
     * Fetch records that have <code>right_identifier_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ScopedIdentifierRelation> fetchRangeOfRightIdentifierId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION.RIGHT_IDENTIFIER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>right_identifier_id IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ScopedIdentifierRelation> fetchByRightIdentifierId(Integer... values) {
        return fetch(ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION.RIGHT_IDENTIFIER_ID, values);
    }

    /**
     * Fetch records that have <code>relation BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ScopedIdentifierRelation> fetchRangeOfRelation(RelationType lowerInclusive, RelationType upperInclusive) {
        return fetchRange(ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION.RELATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>relation IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ScopedIdentifierRelation> fetchByRelation(RelationType... values) {
        return fetch(ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION.RELATION, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ScopedIdentifierRelation> fetchRangeOfCreatedBy(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ScopedIdentifierRelation> fetchByCreatedBy(Integer... values) {
        return fetch(ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ScopedIdentifierRelation> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.ScopedIdentifierRelation> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION.CREATED_AT, values);
    }
}
