/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.daos;


import de.mig.mdr.dal.jooq.enums.ElementType;
import de.mig.mdr.dal.jooq.tables.Staging;
import de.mig.mdr.dal.jooq.tables.records.StagingRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StagingDao extends DAOImpl<StagingRecord, de.mig.mdr.dal.jooq.tables.pojos.Staging, Integer> {

    /**
     * Create a new StagingDao without any configuration
     */
    public StagingDao() {
        super(Staging.STAGING, de.mig.mdr.dal.jooq.tables.pojos.Staging.class);
    }

    /**
     * Create a new StagingDao with an attached configuration
     */
    public StagingDao(Configuration configuration) {
        super(Staging.STAGING, de.mig.mdr.dal.jooq.tables.pojos.Staging.class, configuration);
    }

    @Override
    public Integer getId(de.mig.mdr.dal.jooq.tables.pojos.Staging object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.Staging> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Staging.STAGING.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.Staging> fetchById(Integer... values) {
        return fetch(Staging.STAGING.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.mig.mdr.dal.jooq.tables.pojos.Staging fetchOneById(Integer value) {
        return fetchOne(Staging.STAGING.ID, value);
    }

    /**
     * Fetch records that have <code>data BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.Staging> fetchRangeOfData(String lowerInclusive, String upperInclusive) {
        return fetchRange(Staging.STAGING.DATA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>data IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.Staging> fetchByData(String... values) {
        return fetch(Staging.STAGING.DATA, values);
    }

    /**
     * Fetch records that have <code>element_type BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.Staging> fetchRangeOfElementType(ElementType lowerInclusive, ElementType upperInclusive) {
        return fetchRange(Staging.STAGING.ELEMENT_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>element_type IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.Staging> fetchByElementType(ElementType... values) {
        return fetch(Staging.STAGING.ELEMENT_TYPE, values);
    }

    /**
     * Fetch records that have <code>designation BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.Staging> fetchRangeOfDesignation(String lowerInclusive, String upperInclusive) {
        return fetchRange(Staging.STAGING.DESIGNATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>designation IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.Staging> fetchByDesignation(String... values) {
        return fetch(Staging.STAGING.DESIGNATION, values);
    }

    /**
     * Fetch records that have <code>parent_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.Staging> fetchRangeOfParentId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Staging.STAGING.PARENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.Staging> fetchByParentId(Integer... values) {
        return fetch(Staging.STAGING.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>import_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.Staging> fetchRangeOfImportId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Staging.STAGING.IMPORT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>import_id IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.Staging> fetchByImportId(Integer... values) {
        return fetch(Staging.STAGING.IMPORT_ID, values);
    }

    /**
     * Fetch records that have <code>element_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.Staging> fetchRangeOfElementId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Staging.STAGING.ELEMENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>element_id IN (values)</code>
     */
    public List<de.mig.mdr.dal.jooq.tables.pojos.Staging> fetchByElementId(Integer... values) {
        return fetch(Staging.STAGING.ELEMENT_ID, values);
    }
}
