/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables;


import de.mig.mdr.dal.jooq.Indexes;
import de.mig.mdr.dal.jooq.Public;
import de.mig.mdr.dal.jooq.tables.records.HierarchyRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hierarchy extends TableImpl<HierarchyRecord> {

    private static final long serialVersionUID = 1549770677;

    /**
     * The reference instance of <code>public.hierarchy</code>
     */
    public static final Hierarchy HIERARCHY = new Hierarchy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HierarchyRecord> getRecordType() {
        return HierarchyRecord.class;
    }

    /**
     * The column <code>public.hierarchy.root</code>.
     */
    public final TableField<HierarchyRecord, Integer> ROOT = createField(DSL.name("root"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.hierarchy.super</code>.
     */
    public final TableField<HierarchyRecord, Integer> SUPER = createField(DSL.name("super"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.hierarchy.sub</code>.
     */
    public final TableField<HierarchyRecord, Integer> SUB = createField(DSL.name("sub"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.hierarchy</code> table reference
     */
    public Hierarchy() {
        this(DSL.name("hierarchy"), null);
    }

    /**
     * Create an aliased <code>public.hierarchy</code> table reference
     */
    public Hierarchy(String alias) {
        this(DSL.name(alias), HIERARCHY);
    }

    /**
     * Create an aliased <code>public.hierarchy</code> table reference
     */
    public Hierarchy(Name alias) {
        this(alias, HIERARCHY);
    }

    private Hierarchy(Name alias, Table<HierarchyRecord> aliased) {
        this(alias, aliased, null);
    }

    private Hierarchy(Name alias, Table<HierarchyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.materializedView());
    }

    public <O extends Record> Hierarchy(Table<O> child, ForeignKey<O, HierarchyRecord> key) {
        super(child, key, HIERARCHY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.HIERARCHY_ROOT_IDX, Indexes.HIERARCHY_SUB_IDX, Indexes.HIERARCHY_SUPER_IDX, Indexes.HIERARCHY_SUPER_SUB_IDX);
    }

    @Override
    public Hierarchy as(String alias) {
        return new Hierarchy(DSL.name(alias), this);
    }

    @Override
    public Hierarchy as(Name alias) {
        return new Hierarchy(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Hierarchy rename(String name) {
        return new Hierarchy(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hierarchy rename(Name name) {
        return new Hierarchy(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
