/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables;


import de.mig.mdr.dal.jooq.Public;
import de.mig.mdr.dal.jooq.enums.ElementType;
import de.mig.mdr.dal.jooq.enums.Status;
import de.mig.mdr.dal.jooq.enums.ValidationType;
import de.mig.mdr.dal.jooq.tables.records.IdentifiedElementRecord;

import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IdentifiedElement extends TableImpl<IdentifiedElementRecord> {

    private static final long serialVersionUID = -1269473829;

    /**
     * The reference instance of <code>public.identified_element</code>
     */
    public static final IdentifiedElement IDENTIFIED_ELEMENT = new IdentifiedElement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IdentifiedElementRecord> getRecordType() {
        return IdentifiedElementRecord.class;
    }

    /**
     * The column <code>public.identified_element.si_id</code>.
     */
    public final TableField<IdentifiedElementRecord, Integer> SI_ID = createField(DSL.name("si_id"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.identified_element.si_identifier</code>.
     */
    public final TableField<IdentifiedElementRecord, Integer> SI_IDENTIFIER = createField(DSL.name("si_identifier"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.identified_element.si_version</code>.
     */
    public final TableField<IdentifiedElementRecord, Integer> SI_VERSION = createField(DSL.name("si_version"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.identified_element.si_status</code>.
     */
    public final TableField<IdentifiedElementRecord, Status> SI_STATUS = createField(DSL.name("si_status"), org.jooq.impl.SQLDataType.VARCHAR.asEnumDataType(de.mig.mdr.dal.jooq.enums.Status.class), this, "");

    /**
     * The column <code>public.identified_element.si_namespace_id</code>.
     */
    public final TableField<IdentifiedElementRecord, Integer> SI_NAMESPACE_ID = createField(DSL.name("si_namespace_id"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.identified_element.id</code>.
     */
    public final TableField<IdentifiedElementRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.identified_element.element_type</code>.
     */
    public final TableField<IdentifiedElementRecord, ElementType> ELEMENT_TYPE = createField(DSL.name("element_type"), org.jooq.impl.SQLDataType.VARCHAR.asEnumDataType(de.mig.mdr.dal.jooq.enums.ElementType.class), this, "");

    /**
     * The column <code>public.identified_element.hidden</code>.
     */
    public final TableField<IdentifiedElementRecord, Boolean> HIDDEN = createField(DSL.name("hidden"), org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.identified_element.created_by</code>.
     */
    public final TableField<IdentifiedElementRecord, Integer> CREATED_BY = createField(DSL.name("created_by"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.identified_element.element_id</code>.
     */
    public final TableField<IdentifiedElementRecord, Integer> ELEMENT_ID = createField(DSL.name("element_id"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.identified_element.scoped_identifier_id</code>.
     */
    public final TableField<IdentifiedElementRecord, Integer> SCOPED_IDENTIFIER_ID = createField(DSL.name("scoped_identifier_id"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.identified_element.code</code>.
     */
    public final TableField<IdentifiedElementRecord, String> CODE = createField(DSL.name("code"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.identified_element.is_valid</code>.
     */
    public final TableField<IdentifiedElementRecord, Boolean> IS_VALID = createField(DSL.name("is_valid"), org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.identified_element.format</code>.
     */
    public final TableField<IdentifiedElementRecord, String> FORMAT = createField(DSL.name("format"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.identified_element.datatype</code>.
     */
    public final TableField<IdentifiedElementRecord, String> DATATYPE = createField(DSL.name("datatype"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.identified_element.unit_of_measure</code>.
     */
    public final TableField<IdentifiedElementRecord, String> UNIT_OF_MEASURE = createField(DSL.name("unit_of_measure"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.identified_element.maximum_characters</code>.
     */
    public final TableField<IdentifiedElementRecord, Integer> MAXIMUM_CHARACTERS = createField(DSL.name("maximum_characters"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.identified_element.description</code>.
     */
    public final TableField<IdentifiedElementRecord, String> DESCRIPTION = createField(DSL.name("description"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.identified_element.validation_type</code>.
     */
    public final TableField<IdentifiedElementRecord, ValidationType> VALIDATION_TYPE = createField(DSL.name("validation_type"), org.jooq.impl.SQLDataType.VARCHAR.asEnumDataType(de.mig.mdr.dal.jooq.enums.ValidationType.class), this, "");

    /**
     * The column <code>public.identified_element.validation_data</code>.
     */
    public final TableField<IdentifiedElementRecord, String> VALIDATION_DATA = createField(DSL.name("validation_data"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.identified_element.permitted_value</code>.
     */
    public final TableField<IdentifiedElementRecord, String> PERMITTED_VALUE = createField(DSL.name("permitted_value"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.identified_element.data</code>.
     */
    public final TableField<IdentifiedElementRecord, JSON> DATA = createField(DSL.name("data"), org.jooq.impl.SQLDataType.JSON, this, "");

    /**
     * The column <code>public.identified_element.uuid</code>.
     */
    public final TableField<IdentifiedElementRecord, UUID> UUID = createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>public.identified_element.external_id</code>.
     */
    public final TableField<IdentifiedElementRecord, String> EXTERNAL_ID = createField(DSL.name("external_id"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.identified_element</code> table reference
     */
    public IdentifiedElement() {
        this(DSL.name("identified_element"), null);
    }

    /**
     * Create an aliased <code>public.identified_element</code> table reference
     */
    public IdentifiedElement(String alias) {
        this(DSL.name(alias), IDENTIFIED_ELEMENT);
    }

    /**
     * Create an aliased <code>public.identified_element</code> table reference
     */
    public IdentifiedElement(Name alias) {
        this(alias, IDENTIFIED_ELEMENT);
    }

    private IdentifiedElement(Name alias, Table<IdentifiedElementRecord> aliased) {
        this(alias, aliased, null);
    }

    private IdentifiedElement(Name alias, Table<IdentifiedElementRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("create view \"identified_element\" as  SELECT si.id AS si_id,\n    si.identifier AS si_identifier,\n    si.version AS si_version,\n    si.status AS si_status,\n    si.namespace_id AS si_namespace_id,\n    e.id,\n    e.element_type,\n    e.hidden,\n    e.created_by,\n    e.element_id,\n    e.scoped_identifier_id,\n    e.code,\n    e.is_valid,\n    e.format,\n    e.datatype,\n    e.unit_of_measure,\n    e.maximum_characters,\n    e.description,\n    e.validation_type,\n    e.validation_data,\n    e.permitted_value,\n    e.data,\n    e.uuid,\n    e.external_id\n   FROM ((scoped_identifier si\n     LEFT JOIN element ns ON ((si.namespace_id = ns.id)))\n     LEFT JOIN element e ON ((e.id = si.element_id)));"));
    }

    public <O extends Record> IdentifiedElement(Table<O> child, ForeignKey<O, IdentifiedElementRecord> key) {
        super(child, key, IDENTIFIED_ELEMENT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public IdentifiedElement as(String alias) {
        return new IdentifiedElement(DSL.name(alias), this);
    }

    @Override
    public IdentifiedElement as(Name alias) {
        return new IdentifiedElement(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IdentifiedElement rename(String name) {
        return new IdentifiedElement(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IdentifiedElement rename(Name name) {
        return new IdentifiedElement(name, null);
    }
}
