/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables;


import de.mig.mdr.dal.jooq.Indexes;
import de.mig.mdr.dal.jooq.Keys;
import de.mig.mdr.dal.jooq.Public;
import de.mig.mdr.dal.jooq.tables.records.PermissibleCodeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissibleCode extends TableImpl<PermissibleCodeRecord> {

    private static final long serialVersionUID = -256292884;

    /**
     * The reference instance of <code>public.permissible_code</code>
     */
    public static final PermissibleCode PERMISSIBLE_CODE = new PermissibleCode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PermissibleCodeRecord> getRecordType() {
        return PermissibleCodeRecord.class;
    }

    /**
     * The column <code>public.permissible_code.code_scoped_identifier_id</code>.
     */
    public final TableField<PermissibleCodeRecord, Integer> CODE_SCOPED_IDENTIFIER_ID = createField(DSL.name("code_scoped_identifier_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.permissible_code.catalog_value_domain_id</code>.
     */
    public final TableField<PermissibleCodeRecord, Integer> CATALOG_VALUE_DOMAIN_ID = createField(DSL.name("catalog_value_domain_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.permissible_code</code> table reference
     */
    public PermissibleCode() {
        this(DSL.name("permissible_code"), null);
    }

    /**
     * Create an aliased <code>public.permissible_code</code> table reference
     */
    public PermissibleCode(String alias) {
        this(DSL.name(alias), PERMISSIBLE_CODE);
    }

    /**
     * Create an aliased <code>public.permissible_code</code> table reference
     */
    public PermissibleCode(Name alias) {
        this(alias, PERMISSIBLE_CODE);
    }

    private PermissibleCode(Name alias, Table<PermissibleCodeRecord> aliased) {
        this(alias, aliased, null);
    }

    private PermissibleCode(Name alias, Table<PermissibleCodeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> PermissibleCode(Table<O> child, ForeignKey<O, PermissibleCodeRecord> key) {
        super(child, key, PERMISSIBLE_CODE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PERMISSIBLE_CODE_CATALOG_ID_IDX, Indexes.PERMISSIBLE_CODE_CODE_SCOPED_IDENTIFIER_ID_IDX);
    }

    @Override
    public List<ForeignKey<PermissibleCodeRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PermissibleCodeRecord, ?>>asList(Keys.PERMISSIBLE_CODE__PERMISSIBLE_CODE_CODE_SCOPED_IDENTIFIER_ID_FKEY, Keys.PERMISSIBLE_CODE__PERMISSIBLE_CODE_CATALOG_ID_FKEY);
    }

    public ScopedIdentifier scopedIdentifier() {
        return new ScopedIdentifier(this, Keys.PERMISSIBLE_CODE__PERMISSIBLE_CODE_CODE_SCOPED_IDENTIFIER_ID_FKEY);
    }

    public Element element() {
        return new Element(this, Keys.PERMISSIBLE_CODE__PERMISSIBLE_CODE_CATALOG_ID_FKEY);
    }

    @Override
    public PermissibleCode as(String alias) {
        return new PermissibleCode(DSL.name(alias), this);
    }

    @Override
    public PermissibleCode as(Name alias) {
        return new PermissibleCode(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PermissibleCode rename(String name) {
        return new PermissibleCode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PermissibleCode rename(Name name) {
        return new PermissibleCode(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
