/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq;


import de.mig.mdr.dal.jooq.tables.Definition;
import de.mig.mdr.dal.jooq.tables.Element;
import de.mig.mdr.dal.jooq.tables.Hierarchy;
import de.mig.mdr.dal.jooq.tables.PermissibleCode;
import de.mig.mdr.dal.jooq.tables.ScopedIdentifier;
import de.mig.mdr.dal.jooq.tables.ScopedIdentifierHierarchy;
import de.mig.mdr.dal.jooq.tables.Slot;
import de.mig.mdr.dal.jooq.tables.UserNamespaceGrants;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DEFINITION_ELEMENT_ID_IDX = Indexes0.DEFINITION_ELEMENT_ID_IDX;
    public static final Index DEFINITION_SCOPED_IDENTIFIER_ID_IDX = Indexes0.DEFINITION_SCOPED_IDENTIFIER_ID_IDX;
    public static final Index ELEMENT_CREATED_BY_IDX = Indexes0.ELEMENT_CREATED_BY_IDX;
    public static final Index ELEMENT_ELEMENT_ID_IDX = Indexes0.ELEMENT_ELEMENT_ID_IDX;
    public static final Index ELEMENT_ELEMENT_TYPE_IDX = Indexes0.ELEMENT_ELEMENT_TYPE_IDX;
    public static final Index ELEMENT_ID_ELEMENT_TYPE_IDX = Indexes0.ELEMENT_ID_ELEMENT_TYPE_IDX;
    public static final Index HIERARCHY_ROOT_IDX = Indexes0.HIERARCHY_ROOT_IDX;
    public static final Index HIERARCHY_SUB_IDX = Indexes0.HIERARCHY_SUB_IDX;
    public static final Index HIERARCHY_SUPER_IDX = Indexes0.HIERARCHY_SUPER_IDX;
    public static final Index HIERARCHY_SUPER_SUB_IDX = Indexes0.HIERARCHY_SUPER_SUB_IDX;
    public static final Index PERMISSIBLE_CODE_CATALOG_ID_IDX = Indexes0.PERMISSIBLE_CODE_CATALOG_ID_IDX;
    public static final Index PERMISSIBLE_CODE_CODE_SCOPED_IDENTIFIER_ID_IDX = Indexes0.PERMISSIBLE_CODE_CODE_SCOPED_IDENTIFIER_ID_IDX;
    public static final Index SCOPED_IDENTIFIER_CREATED_BY_IDX = Indexes0.SCOPED_IDENTIFIER_CREATED_BY_IDX;
    public static final Index SCOPED_IDENTIFIER_ELEMENT_ID_IDX = Indexes0.SCOPED_IDENTIFIER_ELEMENT_ID_IDX;
    public static final Index SCOPED_IDENTIFIER_IDENTIFIER_IDX = Indexes0.SCOPED_IDENTIFIER_IDENTIFIER_IDX;
    public static final Index SCOPED_IDENTIFIER_NAMESPACE_ID_IDX = Indexes0.SCOPED_IDENTIFIER_NAMESPACE_ID_IDX;
    public static final Index SCOPED_IDENTIFIER_STATUS_IDX = Indexes0.SCOPED_IDENTIFIER_STATUS_IDX;
    public static final Index SCOPED_IDENTIFIER_UUID_IDX = Indexes0.SCOPED_IDENTIFIER_UUID_IDX;
    public static final Index SCOPED_IDENTIFIER_VERSION_IDX = Indexes0.SCOPED_IDENTIFIER_VERSION_IDX;
    public static final Index SCOPED_IDENTIFIER_HIERARCHY_SUB_ID_IDX = Indexes0.SCOPED_IDENTIFIER_HIERARCHY_SUB_ID_IDX;
    public static final Index SCOPED_IDENTIFIER_HIERARCHY_SUPER_ID_IDX = Indexes0.SCOPED_IDENTIFIER_HIERARCHY_SUPER_ID_IDX;
    public static final Index SLOT_SCOPED_IDENTIFIER_ID_IDX = Indexes0.SLOT_SCOPED_IDENTIFIER_ID_IDX;
    public static final Index USER_NAMESPACE_GRANTS_NAMESPACE_ID_IDX = Indexes0.USER_NAMESPACE_GRANTS_NAMESPACE_ID_IDX;
    public static final Index USER_NAMESPACE_GRANTS_USER_ID_IDX = Indexes0.USER_NAMESPACE_GRANTS_USER_ID_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DEFINITION_ELEMENT_ID_IDX = Internal.createIndex("definition_element_id_idx", Definition.DEFINITION, new OrderField[] { Definition.DEFINITION.ELEMENT_ID }, false);
        public static Index DEFINITION_SCOPED_IDENTIFIER_ID_IDX = Internal.createIndex("definition_scoped_identifier_id_idx", Definition.DEFINITION, new OrderField[] { Definition.DEFINITION.SCOPED_IDENTIFIER_ID }, false);
        public static Index ELEMENT_CREATED_BY_IDX = Internal.createIndex("element_created_by_idx", Element.ELEMENT, new OrderField[] { Element.ELEMENT.CREATED_BY }, false);
        public static Index ELEMENT_ELEMENT_ID_IDX = Internal.createIndex("element_element_id_idx", Element.ELEMENT, new OrderField[] { Element.ELEMENT.ELEMENT_ID }, false);
        public static Index ELEMENT_ELEMENT_TYPE_IDX = Internal.createIndex("element_element_type_idx", Element.ELEMENT, new OrderField[] { Element.ELEMENT.ELEMENT_TYPE }, false);
        public static Index ELEMENT_ID_ELEMENT_TYPE_IDX = Internal.createIndex("element_id_element_type_idx", Element.ELEMENT, new OrderField[] { Element.ELEMENT.ID, Element.ELEMENT.ELEMENT_TYPE }, false);
        public static Index HIERARCHY_ROOT_IDX = Internal.createIndex("hierarchy_root_idx", Hierarchy.HIERARCHY, new OrderField[] { Hierarchy.HIERARCHY.ROOT }, false);
        public static Index HIERARCHY_SUB_IDX = Internal.createIndex("hierarchy_sub_idx", Hierarchy.HIERARCHY, new OrderField[] { Hierarchy.HIERARCHY.SUB }, false);
        public static Index HIERARCHY_SUPER_IDX = Internal.createIndex("hierarchy_super_idx", Hierarchy.HIERARCHY, new OrderField[] { Hierarchy.HIERARCHY.SUPER }, false);
        public static Index HIERARCHY_SUPER_SUB_IDX = Internal.createIndex("hierarchy_super_sub_idx", Hierarchy.HIERARCHY, new OrderField[] { Hierarchy.HIERARCHY.SUPER, Hierarchy.HIERARCHY.SUB }, false);
        public static Index PERMISSIBLE_CODE_CATALOG_ID_IDX = Internal.createIndex("permissible_code_catalog_id_idx", PermissibleCode.PERMISSIBLE_CODE, new OrderField[] { PermissibleCode.PERMISSIBLE_CODE.CATALOG_VALUE_DOMAIN_ID }, false);
        public static Index PERMISSIBLE_CODE_CODE_SCOPED_IDENTIFIER_ID_IDX = Internal.createIndex("permissible_code_code_scoped_identifier_id_idx", PermissibleCode.PERMISSIBLE_CODE, new OrderField[] { PermissibleCode.PERMISSIBLE_CODE.CODE_SCOPED_IDENTIFIER_ID }, false);
        public static Index SCOPED_IDENTIFIER_CREATED_BY_IDX = Internal.createIndex("scoped_identifier_created_by_idx", ScopedIdentifier.SCOPED_IDENTIFIER, new OrderField[] { ScopedIdentifier.SCOPED_IDENTIFIER.CREATED_BY }, false);
        public static Index SCOPED_IDENTIFIER_ELEMENT_ID_IDX = Internal.createIndex("scoped_identifier_element_id_idx", ScopedIdentifier.SCOPED_IDENTIFIER, new OrderField[] { ScopedIdentifier.SCOPED_IDENTIFIER.ELEMENT_ID }, false);
        public static Index SCOPED_IDENTIFIER_IDENTIFIER_IDX = Internal.createIndex("scoped_identifier_identifier_idx", ScopedIdentifier.SCOPED_IDENTIFIER, new OrderField[] { ScopedIdentifier.SCOPED_IDENTIFIER.IDENTIFIER }, false);
        public static Index SCOPED_IDENTIFIER_NAMESPACE_ID_IDX = Internal.createIndex("scoped_identifier_namespace_id_idx", ScopedIdentifier.SCOPED_IDENTIFIER, new OrderField[] { ScopedIdentifier.SCOPED_IDENTIFIER.NAMESPACE_ID }, false);
        public static Index SCOPED_IDENTIFIER_STATUS_IDX = Internal.createIndex("scoped_identifier_status_idx", ScopedIdentifier.SCOPED_IDENTIFIER, new OrderField[] { ScopedIdentifier.SCOPED_IDENTIFIER.STATUS }, false);
        public static Index SCOPED_IDENTIFIER_UUID_IDX = Internal.createIndex("scoped_identifier_uuid_idx", ScopedIdentifier.SCOPED_IDENTIFIER, new OrderField[] { ScopedIdentifier.SCOPED_IDENTIFIER.UUID }, false);
        public static Index SCOPED_IDENTIFIER_VERSION_IDX = Internal.createIndex("scoped_identifier_version_idx", ScopedIdentifier.SCOPED_IDENTIFIER, new OrderField[] { ScopedIdentifier.SCOPED_IDENTIFIER.VERSION }, false);
        public static Index SCOPED_IDENTIFIER_HIERARCHY_SUB_ID_IDX = Internal.createIndex("scoped_identifier_hierarchy_sub_id_idx", ScopedIdentifierHierarchy.SCOPED_IDENTIFIER_HIERARCHY, new OrderField[] { ScopedIdentifierHierarchy.SCOPED_IDENTIFIER_HIERARCHY.SUB_ID }, false);
        public static Index SCOPED_IDENTIFIER_HIERARCHY_SUPER_ID_IDX = Internal.createIndex("scoped_identifier_hierarchy_super_id_idx", ScopedIdentifierHierarchy.SCOPED_IDENTIFIER_HIERARCHY, new OrderField[] { ScopedIdentifierHierarchy.SCOPED_IDENTIFIER_HIERARCHY.SUPER_ID }, false);
        public static Index SLOT_SCOPED_IDENTIFIER_ID_IDX = Internal.createIndex("slot_scoped_identifier_id_idx", Slot.SLOT, new OrderField[] { Slot.SLOT.SCOPED_IDENTIFIER_ID }, false);
        public static Index USER_NAMESPACE_GRANTS_NAMESPACE_ID_IDX = Internal.createIndex("user_namespace_grants_namespace_id_idx", UserNamespaceGrants.USER_NAMESPACE_GRANTS, new OrderField[] { UserNamespaceGrants.USER_NAMESPACE_GRANTS.NAMESPACE_ID }, false);
        public static Index USER_NAMESPACE_GRANTS_USER_ID_IDX = Internal.createIndex("user_namespace_grants_user_id_idx", UserNamespaceGrants.USER_NAMESPACE_GRANTS, new OrderField[] { UserNamespaceGrants.USER_NAMESPACE_GRANTS.USER_ID }, false);
    }
}
