/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.concepts_id_seq</code>
     */
    public static final Sequence<Long> CONCEPTS_ID_SEQ = Internal.createSequence("concepts_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.config_id_seq</code>
     */
    public static final Sequence<Long> CONFIG_ID_SEQ = Internal.createSequence("config_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.definition_id_seq</code>
     */
    public static final Sequence<Long> DEFINITION_ID_SEQ = Internal.createSequence("definition_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.element_id_seq</code>
     */
    public static final Sequence<Long> ELEMENT_ID_SEQ = Internal.createSequence("element_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.import_id_seq</code>
     */
    public static final Sequence<Long> IMPORT_ID_SEQ = Internal.createSequence("import_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.mdr_user_id_seq</code>
     */
    public static final Sequence<Long> MDR_USER_ID_SEQ = Internal.createSequence("mdr_user_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.scoped_identifier_id_seq</code>
     */
    public static final Sequence<Long> SCOPED_IDENTIFIER_ID_SEQ = Internal.createSequence("scoped_identifier_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.slot_id_seq</code>
     */
    public static final Sequence<Long> SLOT_ID_SEQ = Internal.createSequence("slot_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.source_id_seq</code>
     */
    public static final Sequence<Long> SOURCE_ID_SEQ = Internal.createSequence("source_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.staging_id_seq</code>
     */
    public static final Sequence<Long> STAGING_ID_SEQ = Internal.createSequence("staging_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
