/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq;


import de.mig.mdr.dal.jooq.tables.ConceptElementAssociations;
import de.mig.mdr.dal.jooq.tables.Concepts;
import de.mig.mdr.dal.jooq.tables.Config;
import de.mig.mdr.dal.jooq.tables.Definition;
import de.mig.mdr.dal.jooq.tables.Element;
import de.mig.mdr.dal.jooq.tables.GetDefinitionByUrn;
import de.mig.mdr.dal.jooq.tables.GetSlotByUrn;
import de.mig.mdr.dal.jooq.tables.GetValueDomainByUrn;
import de.mig.mdr.dal.jooq.tables.Hierarchy;
import de.mig.mdr.dal.jooq.tables.IdentifiedElement;
import de.mig.mdr.dal.jooq.tables.Import;
import de.mig.mdr.dal.jooq.tables.MdrUser;
import de.mig.mdr.dal.jooq.tables.PermissibleCode;
import de.mig.mdr.dal.jooq.tables.ScopedIdentifier;
import de.mig.mdr.dal.jooq.tables.ScopedIdentifierHierarchy;
import de.mig.mdr.dal.jooq.tables.ScopedIdentifierRelation;
import de.mig.mdr.dal.jooq.tables.Slot;
import de.mig.mdr.dal.jooq.tables.Source;
import de.mig.mdr.dal.jooq.tables.Staging;
import de.mig.mdr.dal.jooq.tables.UserNamespaceGrants;
import de.mig.mdr.dal.jooq.tables.UserSourceCredentials;
import de.mig.mdr.dal.jooq.tables.records.GetDefinitionByUrnRecord;
import de.mig.mdr.dal.jooq.tables.records.GetSlotByUrnRecord;
import de.mig.mdr.dal.jooq.tables.records.GetValueDomainByUrnRecord;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.concept_element_associations</code>.
     */
    public static final ConceptElementAssociations CONCEPT_ELEMENT_ASSOCIATIONS = ConceptElementAssociations.CONCEPT_ELEMENT_ASSOCIATIONS;

    /**
     * The table <code>public.concepts</code>.
     */
    public static final Concepts CONCEPTS = Concepts.CONCEPTS;

    /**
     * The table <code>public.config</code>.
     */
    public static final Config CONFIG = Config.CONFIG;

    /**
     * The table <code>public.definition</code>.
     */
    public static final Definition DEFINITION = Definition.DEFINITION;

    /**
     * The table <code>public.element</code>.
     */
    public static final Element ELEMENT = Element.ELEMENT;

    /**
     * The table <code>public.get_definition_by_urn</code>.
     */
    public static final GetDefinitionByUrn GET_DEFINITION_BY_URN = GetDefinitionByUrn.GET_DEFINITION_BY_URN;

    /**
     * Call <code>public.get_definition_by_urn</code>.
     */
    public static Result<GetDefinitionByUrnRecord> GET_DEFINITION_BY_URN(Configuration configuration, String urn) {
        return configuration.dsl().selectFrom(de.mig.mdr.dal.jooq.tables.GetDefinitionByUrn.GET_DEFINITION_BY_URN.call(urn)).fetch();
    }

    /**
     * Get <code>public.get_definition_by_urn</code> as a table.
     */
    public static GetDefinitionByUrn GET_DEFINITION_BY_URN(String urn) {
        return de.mig.mdr.dal.jooq.tables.GetDefinitionByUrn.GET_DEFINITION_BY_URN.call(urn);
    }

    /**
     * Get <code>public.get_definition_by_urn</code> as a table.
     */
    public static GetDefinitionByUrn GET_DEFINITION_BY_URN(Field<String> urn) {
        return de.mig.mdr.dal.jooq.tables.GetDefinitionByUrn.GET_DEFINITION_BY_URN.call(urn);
    }

    /**
     * The table <code>public.get_slot_by_urn</code>.
     */
    public static final GetSlotByUrn GET_SLOT_BY_URN = GetSlotByUrn.GET_SLOT_BY_URN;

    /**
     * Call <code>public.get_slot_by_urn</code>.
     */
    public static Result<GetSlotByUrnRecord> GET_SLOT_BY_URN(Configuration configuration, String urn) {
        return configuration.dsl().selectFrom(de.mig.mdr.dal.jooq.tables.GetSlotByUrn.GET_SLOT_BY_URN.call(urn)).fetch();
    }

    /**
     * Get <code>public.get_slot_by_urn</code> as a table.
     */
    public static GetSlotByUrn GET_SLOT_BY_URN(String urn) {
        return de.mig.mdr.dal.jooq.tables.GetSlotByUrn.GET_SLOT_BY_URN.call(urn);
    }

    /**
     * Get <code>public.get_slot_by_urn</code> as a table.
     */
    public static GetSlotByUrn GET_SLOT_BY_URN(Field<String> urn) {
        return de.mig.mdr.dal.jooq.tables.GetSlotByUrn.GET_SLOT_BY_URN.call(urn);
    }

    /**
     * The table <code>public.get_value_domain_by_urn</code>.
     */
    public static final GetValueDomainByUrn GET_VALUE_DOMAIN_BY_URN = GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN;

    /**
     * Call <code>public.get_value_domain_by_urn</code>.
     */
    public static Result<GetValueDomainByUrnRecord> GET_VALUE_DOMAIN_BY_URN(Configuration configuration, String urn) {
        return configuration.dsl().selectFrom(de.mig.mdr.dal.jooq.tables.GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.call(urn)).fetch();
    }

    /**
     * Get <code>public.get_value_domain_by_urn</code> as a table.
     */
    public static GetValueDomainByUrn GET_VALUE_DOMAIN_BY_URN(String urn) {
        return de.mig.mdr.dal.jooq.tables.GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.call(urn);
    }

    /**
     * Get <code>public.get_value_domain_by_urn</code> as a table.
     */
    public static GetValueDomainByUrn GET_VALUE_DOMAIN_BY_URN(Field<String> urn) {
        return de.mig.mdr.dal.jooq.tables.GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.call(urn);
    }

    /**
     * The table <code>public.hierarchy</code>.
     */
    public static final Hierarchy HIERARCHY = Hierarchy.HIERARCHY;

    /**
     * The table <code>public.identified_element</code>.
     */
    public static final IdentifiedElement IDENTIFIED_ELEMENT = IdentifiedElement.IDENTIFIED_ELEMENT;

    /**
     * The table <code>public.import</code>.
     */
    public static final Import IMPORT = Import.IMPORT;

    /**
     * The table <code>public.mdr_user</code>.
     */
    public static final MdrUser MDR_USER = MdrUser.MDR_USER;

    /**
     * The table <code>public.permissible_code</code>.
     */
    public static final PermissibleCode PERMISSIBLE_CODE = PermissibleCode.PERMISSIBLE_CODE;

    /**
     * The table <code>public.scoped_identifier</code>.
     */
    public static final ScopedIdentifier SCOPED_IDENTIFIER = ScopedIdentifier.SCOPED_IDENTIFIER;

    /**
     * The table <code>public.scoped_identifier_hierarchy</code>.
     */
    public static final ScopedIdentifierHierarchy SCOPED_IDENTIFIER_HIERARCHY = ScopedIdentifierHierarchy.SCOPED_IDENTIFIER_HIERARCHY;

    /**
     * The table <code>public.scoped_identifier_relation</code>.
     */
    public static final ScopedIdentifierRelation SCOPED_IDENTIFIER_RELATION = ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION;

    /**
     * The table <code>public.slot</code>.
     */
    public static final Slot SLOT = Slot.SLOT;

    /**
     * The table <code>public.source</code>.
     */
    public static final Source SOURCE = Source.SOURCE;

    /**
     * The table <code>public.staging</code>.
     */
    public static final Staging STAGING = Staging.STAGING;

    /**
     * The table <code>public.user_namespace_grants</code>.
     */
    public static final UserNamespaceGrants USER_NAMESPACE_GRANTS = UserNamespaceGrants.USER_NAMESPACE_GRANTS;

    /**
     * The table <code>public.user_source_credentials</code>.
     */
    public static final UserSourceCredentials USER_SOURCE_CREDENTIALS = UserSourceCredentials.USER_SOURCE_CREDENTIALS;
}
