/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.routines;


import de.mig.mdr.dal.jooq.Public;
import de.mig.mdr.dal.jooq.tables.records.ScopedIdentifierRecord;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Urn extends AbstractRoutine<String> {

    private static final long serialVersionUID = 1229671972;

    /**
     * The parameter <code>public.urn.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.urn.sc</code>.
     */
    public static final Parameter<ScopedIdentifierRecord> SC = Internal.createParameter("sc", de.mig.mdr.dal.jooq.tables.ScopedIdentifier.SCOPED_IDENTIFIER.getDataType(), false, false);

    /**
     * Create a new routine call instance
     */
    public Urn() {
        super("urn", Public.PUBLIC, org.jooq.impl.SQLDataType.CLOB);

        setReturnParameter(RETURN_VALUE);
        addInParameter(SC);
    }

    /**
     * Set the <code>sc</code> parameter IN value to the routine
     */
    public void setSc(ScopedIdentifierRecord value) {
        setValue(SC, value);
    }

    /**
     * Set the <code>sc</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setSc(Field<ScopedIdentifierRecord> field) {
        setField(SC, field);
    }
}
