/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.records;


import de.mig.mdr.dal.jooq.tables.Concepts;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConceptsRecord extends UpdatableRecordImpl<ConceptsRecord> implements Record8<Integer, String, String, String, String, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = 108596030;

    /**
     * Setter for <code>public.concepts.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.concepts.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.concepts.system</code>.
     */
    public void setSystem(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.concepts.system</code>.
     */
    public String getSystem() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.concepts.version</code>.
     */
    public void setVersion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.concepts.version</code>.
     */
    public String getVersion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.concepts.term</code>.
     */
    public void setTerm(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.concepts.term</code>.
     */
    public String getTerm() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.concepts.text</code>.
     */
    public void setText(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.concepts.text</code>.
     */
    public String getText() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.concepts.source_id</code>.
     */
    public void setSourceId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.concepts.source_id</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.concepts.created_by</code>.
     */
    public void setCreatedBy(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.concepts.created_by</code>.
     */
    public Integer getCreatedBy() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.concepts.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.concepts.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, String, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, String, String, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Concepts.CONCEPTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Concepts.CONCEPTS.SYSTEM;
    }

    @Override
    public Field<String> field3() {
        return Concepts.CONCEPTS.VERSION;
    }

    @Override
    public Field<String> field4() {
        return Concepts.CONCEPTS.TERM;
    }

    @Override
    public Field<String> field5() {
        return Concepts.CONCEPTS.TEXT;
    }

    @Override
    public Field<Integer> field6() {
        return Concepts.CONCEPTS.SOURCE_ID;
    }

    @Override
    public Field<Integer> field7() {
        return Concepts.CONCEPTS.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Concepts.CONCEPTS.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSystem();
    }

    @Override
    public String component3() {
        return getVersion();
    }

    @Override
    public String component4() {
        return getTerm();
    }

    @Override
    public String component5() {
        return getText();
    }

    @Override
    public Integer component6() {
        return getSourceId();
    }

    @Override
    public Integer component7() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSystem();
    }

    @Override
    public String value3() {
        return getVersion();
    }

    @Override
    public String value4() {
        return getTerm();
    }

    @Override
    public String value5() {
        return getText();
    }

    @Override
    public Integer value6() {
        return getSourceId();
    }

    @Override
    public Integer value7() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public ConceptsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ConceptsRecord value2(String value) {
        setSystem(value);
        return this;
    }

    @Override
    public ConceptsRecord value3(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public ConceptsRecord value4(String value) {
        setTerm(value);
        return this;
    }

    @Override
    public ConceptsRecord value5(String value) {
        setText(value);
        return this;
    }

    @Override
    public ConceptsRecord value6(Integer value) {
        setSourceId(value);
        return this;
    }

    @Override
    public ConceptsRecord value7(Integer value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public ConceptsRecord value8(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ConceptsRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, Integer value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConceptsRecord
     */
    public ConceptsRecord() {
        super(Concepts.CONCEPTS);
    }

    /**
     * Create a detached, initialised ConceptsRecord
     */
    public ConceptsRecord(Integer id, String system, String version, String term, String text, Integer sourceId, Integer createdBy, LocalDateTime createdAt) {
        super(Concepts.CONCEPTS);

        set(0, id);
        set(1, system);
        set(2, version);
        set(3, term);
        set(4, text);
        set(5, sourceId);
        set(6, createdBy);
        set(7, createdAt);
    }
}
