/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.records;


import de.mig.mdr.dal.jooq.enums.ElementType;
import de.mig.mdr.dal.jooq.enums.ValidationType;
import de.mig.mdr.dal.jooq.tables.GetValueDomainByUrn;

import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetValueDomainByUrnRecord extends TableRecordImpl<GetValueDomainByUrnRecord> implements Record19<Integer, ElementType, Boolean, Integer, Integer, Integer, String, Boolean, String, String, String, Integer, String, ValidationType, String, String, JSON, UUID, String> {

    private static final long serialVersionUID = -590293225;

    /**
     * Setter for <code>public.get_value_domain_by_urn.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.element_type</code>.
     */
    public void setElementType(ElementType value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.element_type</code>.
     */
    public ElementType getElementType() {
        return (ElementType) get(1);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.hidden</code>.
     */
    public void setHidden(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.hidden</code>.
     */
    public Boolean getHidden() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.created_by</code>.
     */
    public void setCreatedBy(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.created_by</code>.
     */
    public Integer getCreatedBy() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.element_id</code>.
     */
    public void setElementId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.element_id</code>.
     */
    public Integer getElementId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.scoped_identifier_id</code>.
     */
    public void setScopedIdentifierId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.scoped_identifier_id</code>.
     */
    public Integer getScopedIdentifierId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.code</code>.
     */
    public void setCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.code</code>.
     */
    public String getCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.is_valid</code>.
     */
    public void setIsValid(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.is_valid</code>.
     */
    public Boolean getIsValid() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.format</code>.
     */
    public void setFormat(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.format</code>.
     */
    public String getFormat() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.datatype</code>.
     */
    public void setDatatype(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.datatype</code>.
     */
    public String getDatatype() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.unit_of_measure</code>.
     */
    public void setUnitOfMeasure(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.unit_of_measure</code>.
     */
    public String getUnitOfMeasure() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.maximum_characters</code>.
     */
    public void setMaximumCharacters(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.maximum_characters</code>.
     */
    public Integer getMaximumCharacters() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.description</code>.
     */
    public void setDescription(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.description</code>.
     */
    public String getDescription() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.validation_type</code>.
     */
    public void setValidationType(ValidationType value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.validation_type</code>.
     */
    public ValidationType getValidationType() {
        return (ValidationType) get(13);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.validation_data</code>.
     */
    public void setValidationData(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.validation_data</code>.
     */
    public String getValidationData() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.permitted_value</code>.
     */
    public void setPermittedValue(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.permitted_value</code>.
     */
    public String getPermittedValue() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.data</code>.
     */
    public void setData(JSON value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.data</code>.
     */
    public JSON getData() {
        return (JSON) get(16);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(17);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.external_id</code>.
     */
    public void setExternalId(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.external_id</code>.
     */
    public String getExternalId() {
        return (String) get(18);
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<Integer, ElementType, Boolean, Integer, Integer, Integer, String, Boolean, String, String, String, Integer, String, ValidationType, String, String, JSON, UUID, String> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<Integer, ElementType, Boolean, Integer, Integer, Integer, String, Boolean, String, String, String, Integer, String, ValidationType, String, String, JSON, UUID, String> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.ID;
    }

    @Override
    public Field<ElementType> field2() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.ELEMENT_TYPE;
    }

    @Override
    public Field<Boolean> field3() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.HIDDEN;
    }

    @Override
    public Field<Integer> field4() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.CREATED_BY;
    }

    @Override
    public Field<Integer> field5() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.ELEMENT_ID;
    }

    @Override
    public Field<Integer> field6() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.SCOPED_IDENTIFIER_ID;
    }

    @Override
    public Field<String> field7() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.CODE;
    }

    @Override
    public Field<Boolean> field8() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.IS_VALID;
    }

    @Override
    public Field<String> field9() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.FORMAT;
    }

    @Override
    public Field<String> field10() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.DATATYPE;
    }

    @Override
    public Field<String> field11() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.UNIT_OF_MEASURE;
    }

    @Override
    public Field<Integer> field12() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.MAXIMUM_CHARACTERS;
    }

    @Override
    public Field<String> field13() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.DESCRIPTION;
    }

    @Override
    public Field<ValidationType> field14() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.VALIDATION_TYPE;
    }

    @Override
    public Field<String> field15() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.VALIDATION_DATA;
    }

    @Override
    public Field<String> field16() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.PERMITTED_VALUE;
    }

    @Override
    public Field<JSON> field17() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.DATA;
    }

    @Override
    public Field<UUID> field18() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.UUID;
    }

    @Override
    public Field<String> field19() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.EXTERNAL_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public ElementType component2() {
        return getElementType();
    }

    @Override
    public Boolean component3() {
        return getHidden();
    }

    @Override
    public Integer component4() {
        return getCreatedBy();
    }

    @Override
    public Integer component5() {
        return getElementId();
    }

    @Override
    public Integer component6() {
        return getScopedIdentifierId();
    }

    @Override
    public String component7() {
        return getCode();
    }

    @Override
    public Boolean component8() {
        return getIsValid();
    }

    @Override
    public String component9() {
        return getFormat();
    }

    @Override
    public String component10() {
        return getDatatype();
    }

    @Override
    public String component11() {
        return getUnitOfMeasure();
    }

    @Override
    public Integer component12() {
        return getMaximumCharacters();
    }

    @Override
    public String component13() {
        return getDescription();
    }

    @Override
    public ValidationType component14() {
        return getValidationType();
    }

    @Override
    public String component15() {
        return getValidationData();
    }

    @Override
    public String component16() {
        return getPermittedValue();
    }

    @Override
    public JSON component17() {
        return getData();
    }

    @Override
    public UUID component18() {
        return getUuid();
    }

    @Override
    public String component19() {
        return getExternalId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public ElementType value2() {
        return getElementType();
    }

    @Override
    public Boolean value3() {
        return getHidden();
    }

    @Override
    public Integer value4() {
        return getCreatedBy();
    }

    @Override
    public Integer value5() {
        return getElementId();
    }

    @Override
    public Integer value6() {
        return getScopedIdentifierId();
    }

    @Override
    public String value7() {
        return getCode();
    }

    @Override
    public Boolean value8() {
        return getIsValid();
    }

    @Override
    public String value9() {
        return getFormat();
    }

    @Override
    public String value10() {
        return getDatatype();
    }

    @Override
    public String value11() {
        return getUnitOfMeasure();
    }

    @Override
    public Integer value12() {
        return getMaximumCharacters();
    }

    @Override
    public String value13() {
        return getDescription();
    }

    @Override
    public ValidationType value14() {
        return getValidationType();
    }

    @Override
    public String value15() {
        return getValidationData();
    }

    @Override
    public String value16() {
        return getPermittedValue();
    }

    @Override
    public JSON value17() {
        return getData();
    }

    @Override
    public UUID value18() {
        return getUuid();
    }

    @Override
    public String value19() {
        return getExternalId();
    }

    @Override
    public GetValueDomainByUrnRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value2(ElementType value) {
        setElementType(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value3(Boolean value) {
        setHidden(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value4(Integer value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value5(Integer value) {
        setElementId(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value6(Integer value) {
        setScopedIdentifierId(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value7(String value) {
        setCode(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value8(Boolean value) {
        setIsValid(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value9(String value) {
        setFormat(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value10(String value) {
        setDatatype(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value11(String value) {
        setUnitOfMeasure(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value12(Integer value) {
        setMaximumCharacters(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value13(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value14(ValidationType value) {
        setValidationType(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value15(String value) {
        setValidationData(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value16(String value) {
        setPermittedValue(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value17(JSON value) {
        setData(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value18(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value19(String value) {
        setExternalId(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord values(Integer value1, ElementType value2, Boolean value3, Integer value4, Integer value5, Integer value6, String value7, Boolean value8, String value9, String value10, String value11, Integer value12, String value13, ValidationType value14, String value15, String value16, JSON value17, UUID value18, String value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetValueDomainByUrnRecord
     */
    public GetValueDomainByUrnRecord() {
        super(GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN);
    }

    /**
     * Create a detached, initialised GetValueDomainByUrnRecord
     */
    public GetValueDomainByUrnRecord(Integer id, ElementType elementType, Boolean hidden, Integer createdBy, Integer elementId, Integer scopedIdentifierId, String code, Boolean isValid, String format, String datatype, String unitOfMeasure, Integer maximumCharacters, String description, ValidationType validationType, String validationData, String permittedValue, JSON data, UUID uuid, String externalId) {
        super(GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN);

        set(0, id);
        set(1, elementType);
        set(2, hidden);
        set(3, createdBy);
        set(4, elementId);
        set(5, scopedIdentifierId);
        set(6, code);
        set(7, isValid);
        set(8, format);
        set(9, datatype);
        set(10, unitOfMeasure);
        set(11, maximumCharacters);
        set(12, description);
        set(13, validationType);
        set(14, validationData);
        set(15, permittedValue);
        set(16, data);
        set(17, uuid);
        set(18, externalId);
    }
}
