/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.records;


import de.mig.mdr.dal.jooq.tables.MdrUser;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdrUserRecord extends UpdatableRecordImpl<MdrUserRecord> implements Record6<Integer, String, String, String, String, String> {

    private static final long serialVersionUID = 1926031502;

    /**
     * Setter for <code>public.mdr_user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mdr_user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.mdr_user.auth_id</code>.
     */
    public void setAuthId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mdr_user.auth_id</code>.
     */
    public String getAuthId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.mdr_user.first_name</code>.
     */
    public void setFirstName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mdr_user.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mdr_user.last_name</code>.
     */
    public void setLastName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mdr_user.last_name</code>.
     */
    public String getLastName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mdr_user.user_name</code>.
     */
    public void setUserName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mdr_user.user_name</code>.
     */
    public String getUserName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mdr_user.email</code>.
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mdr_user.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MdrUser.MDR_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return MdrUser.MDR_USER.AUTH_ID;
    }

    @Override
    public Field<String> field3() {
        return MdrUser.MDR_USER.FIRST_NAME;
    }

    @Override
    public Field<String> field4() {
        return MdrUser.MDR_USER.LAST_NAME;
    }

    @Override
    public Field<String> field5() {
        return MdrUser.MDR_USER.USER_NAME;
    }

    @Override
    public Field<String> field6() {
        return MdrUser.MDR_USER.EMAIL;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAuthId();
    }

    @Override
    public String component3() {
        return getFirstName();
    }

    @Override
    public String component4() {
        return getLastName();
    }

    @Override
    public String component5() {
        return getUserName();
    }

    @Override
    public String component6() {
        return getEmail();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAuthId();
    }

    @Override
    public String value3() {
        return getFirstName();
    }

    @Override
    public String value4() {
        return getLastName();
    }

    @Override
    public String value5() {
        return getUserName();
    }

    @Override
    public String value6() {
        return getEmail();
    }

    @Override
    public MdrUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MdrUserRecord value2(String value) {
        setAuthId(value);
        return this;
    }

    @Override
    public MdrUserRecord value3(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public MdrUserRecord value4(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public MdrUserRecord value5(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public MdrUserRecord value6(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public MdrUserRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MdrUserRecord
     */
    public MdrUserRecord() {
        super(MdrUser.MDR_USER);
    }

    /**
     * Create a detached, initialised MdrUserRecord
     */
    public MdrUserRecord(Integer id, String authId, String firstName, String lastName, String userName, String email) {
        super(MdrUser.MDR_USER);

        set(0, id);
        set(1, authId);
        set(2, firstName);
        set(3, lastName);
        set(4, userName);
        set(5, email);
    }
}
