/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.records;


import de.mig.mdr.dal.jooq.enums.ElementType;
import de.mig.mdr.dal.jooq.enums.Status;
import de.mig.mdr.dal.jooq.tables.ScopedIdentifier;

import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScopedIdentifierRecord extends UpdatableRecordImpl<ScopedIdentifierRecord> implements Record10<Integer, ElementType, Integer, Integer, String, Integer, Status, Integer, Integer, UUID> {

    private static final long serialVersionUID = 1535439116;

    /**
     * Setter for <code>public.scoped_identifier.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.scoped_identifier.element_type</code>.
     */
    public void setElementType(ElementType value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.element_type</code>.
     */
    public ElementType getElementType() {
        return (ElementType) get(1);
    }

    /**
     * Setter for <code>public.scoped_identifier.version</code>.
     */
    public void setVersion(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.scoped_identifier.identifier</code>.
     */
    public void setIdentifier(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.identifier</code>.
     */
    public Integer getIdentifier() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.scoped_identifier.url</code>.
     */
    public void setUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.url</code>.
     */
    public String getUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.scoped_identifier.created_by</code>.
     */
    public void setCreatedBy(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.created_by</code>.
     */
    public Integer getCreatedBy() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.scoped_identifier.status</code>.
     */
    public void setStatus(Status value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.status</code>.
     */
    public Status getStatus() {
        return (Status) get(6);
    }

    /**
     * Setter for <code>public.scoped_identifier.element_id</code>.
     */
    public void setElementId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.element_id</code>.
     */
    public Integer getElementId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.scoped_identifier.namespace_id</code>.
     */
    public void setNamespaceId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.namespace_id</code>.
     */
    public Integer getNamespaceId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.scoped_identifier.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, ElementType, Integer, Integer, String, Integer, Status, Integer, Integer, UUID> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, ElementType, Integer, Integer, String, Integer, Status, Integer, Integer, UUID> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.ID;
    }

    @Override
    public Field<ElementType> field2() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.ELEMENT_TYPE;
    }

    @Override
    public Field<Integer> field3() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.VERSION;
    }

    @Override
    public Field<Integer> field4() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.IDENTIFIER;
    }

    @Override
    public Field<String> field5() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.URL;
    }

    @Override
    public Field<Integer> field6() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.CREATED_BY;
    }

    @Override
    public Field<Status> field7() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.STATUS;
    }

    @Override
    public Field<Integer> field8() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.ELEMENT_ID;
    }

    @Override
    public Field<Integer> field9() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.NAMESPACE_ID;
    }

    @Override
    public Field<UUID> field10() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.UUID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public ElementType component2() {
        return getElementType();
    }

    @Override
    public Integer component3() {
        return getVersion();
    }

    @Override
    public Integer component4() {
        return getIdentifier();
    }

    @Override
    public String component5() {
        return getUrl();
    }

    @Override
    public Integer component6() {
        return getCreatedBy();
    }

    @Override
    public Status component7() {
        return getStatus();
    }

    @Override
    public Integer component8() {
        return getElementId();
    }

    @Override
    public Integer component9() {
        return getNamespaceId();
    }

    @Override
    public UUID component10() {
        return getUuid();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public ElementType value2() {
        return getElementType();
    }

    @Override
    public Integer value3() {
        return getVersion();
    }

    @Override
    public Integer value4() {
        return getIdentifier();
    }

    @Override
    public String value5() {
        return getUrl();
    }

    @Override
    public Integer value6() {
        return getCreatedBy();
    }

    @Override
    public Status value7() {
        return getStatus();
    }

    @Override
    public Integer value8() {
        return getElementId();
    }

    @Override
    public Integer value9() {
        return getNamespaceId();
    }

    @Override
    public UUID value10() {
        return getUuid();
    }

    @Override
    public ScopedIdentifierRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord value2(ElementType value) {
        setElementType(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord value3(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord value4(Integer value) {
        setIdentifier(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord value5(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord value6(Integer value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord value7(Status value) {
        setStatus(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord value8(Integer value) {
        setElementId(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord value9(Integer value) {
        setNamespaceId(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord value10(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord values(Integer value1, ElementType value2, Integer value3, Integer value4, String value5, Integer value6, Status value7, Integer value8, Integer value9, UUID value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScopedIdentifierRecord
     */
    public ScopedIdentifierRecord() {
        super(ScopedIdentifier.SCOPED_IDENTIFIER);
    }

    /**
     * Create a detached, initialised ScopedIdentifierRecord
     */
    public ScopedIdentifierRecord(Integer id, ElementType elementType, Integer version, Integer identifier, String url, Integer createdBy, Status status, Integer elementId, Integer namespaceId, UUID uuid) {
        super(ScopedIdentifier.SCOPED_IDENTIFIER);

        set(0, id);
        set(1, elementType);
        set(2, version);
        set(3, identifier);
        set(4, url);
        set(5, createdBy);
        set(6, status);
        set(7, elementId);
        set(8, namespaceId);
        set(9, uuid);
    }
}
