/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.records;


import de.mig.mdr.dal.jooq.enums.RelationType;
import de.mig.mdr.dal.jooq.tables.ScopedIdentifierRelation;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScopedIdentifierRelationRecord extends UpdatableRecordImpl<ScopedIdentifierRelationRecord> implements Record5<Integer, Integer, RelationType, Integer, LocalDateTime> {

    private static final long serialVersionUID = -1091960471;

    /**
     * Setter for <code>public.scoped_identifier_relation.left_identifier_id</code>.
     */
    public void setLeftIdentifierId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.scoped_identifier_relation.left_identifier_id</code>.
     */
    public Integer getLeftIdentifierId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.scoped_identifier_relation.right_identifier_id</code>.
     */
    public void setRightIdentifierId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.scoped_identifier_relation.right_identifier_id</code>.
     */
    public Integer getRightIdentifierId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.scoped_identifier_relation.relation</code>.
     */
    public void setRelation(RelationType value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.scoped_identifier_relation.relation</code>.
     */
    public RelationType getRelation() {
        return (RelationType) get(2);
    }

    /**
     * Setter for <code>public.scoped_identifier_relation.created_by</code>.
     */
    public void setCreatedBy(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.scoped_identifier_relation.created_by</code>.
     */
    public Integer getCreatedBy() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.scoped_identifier_relation.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.scoped_identifier_relation.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, RelationType, Integer, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, RelationType, Integer, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION.LEFT_IDENTIFIER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION.RIGHT_IDENTIFIER_ID;
    }

    @Override
    public Field<RelationType> field3() {
        return ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION.RELATION;
    }

    @Override
    public Field<Integer> field4() {
        return ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getLeftIdentifierId();
    }

    @Override
    public Integer component2() {
        return getRightIdentifierId();
    }

    @Override
    public RelationType component3() {
        return getRelation();
    }

    @Override
    public Integer component4() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getLeftIdentifierId();
    }

    @Override
    public Integer value2() {
        return getRightIdentifierId();
    }

    @Override
    public RelationType value3() {
        return getRelation();
    }

    @Override
    public Integer value4() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public ScopedIdentifierRelationRecord value1(Integer value) {
        setLeftIdentifierId(value);
        return this;
    }

    @Override
    public ScopedIdentifierRelationRecord value2(Integer value) {
        setRightIdentifierId(value);
        return this;
    }

    @Override
    public ScopedIdentifierRelationRecord value3(RelationType value) {
        setRelation(value);
        return this;
    }

    @Override
    public ScopedIdentifierRelationRecord value4(Integer value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public ScopedIdentifierRelationRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ScopedIdentifierRelationRecord values(Integer value1, Integer value2, RelationType value3, Integer value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScopedIdentifierRelationRecord
     */
    public ScopedIdentifierRelationRecord() {
        super(ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION);
    }

    /**
     * Create a detached, initialised ScopedIdentifierRelationRecord
     */
    public ScopedIdentifierRelationRecord(Integer leftIdentifierId, Integer rightIdentifierId, RelationType relation, Integer createdBy, LocalDateTime createdAt) {
        super(ScopedIdentifierRelation.SCOPED_IDENTIFIER_RELATION);

        set(0, leftIdentifierId);
        set(1, rightIdentifierId);
        set(2, relation);
        set(3, createdBy);
        set(4, createdAt);
    }
}
