/*
 * This file is generated by jOOQ.
 */
package de.mig.mdr.dal.jooq.tables.records;


import de.mig.mdr.dal.jooq.enums.ElementType;
import de.mig.mdr.dal.jooq.tables.Staging;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StagingRecord extends UpdatableRecordImpl<StagingRecord> implements Record7<Integer, String, ElementType, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = -1362150249;

    /**
     * Setter for <code>public.staging.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.staging.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.staging.data</code>.
     */
    public void setData(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.staging.data</code>.
     */
    public String getData() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.staging.element_type</code>.
     */
    public void setElementType(ElementType value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.staging.element_type</code>.
     */
    public ElementType getElementType() {
        return (ElementType) get(2);
    }

    /**
     * Setter for <code>public.staging.designation</code>.
     */
    public void setDesignation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.staging.designation</code>.
     */
    public String getDesignation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.staging.parent_id</code>.
     */
    public void setParentId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.staging.parent_id</code>.
     */
    public Integer getParentId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.staging.import_id</code>.
     */
    public void setImportId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.staging.import_id</code>.
     */
    public Integer getImportId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.staging.element_id</code>.
     */
    public void setElementId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.staging.element_id</code>.
     */
    public Integer getElementId() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, ElementType, String, Integer, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, ElementType, String, Integer, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Staging.STAGING.ID;
    }

    @Override
    public Field<String> field2() {
        return Staging.STAGING.DATA;
    }

    @Override
    public Field<ElementType> field3() {
        return Staging.STAGING.ELEMENT_TYPE;
    }

    @Override
    public Field<String> field4() {
        return Staging.STAGING.DESIGNATION;
    }

    @Override
    public Field<Integer> field5() {
        return Staging.STAGING.PARENT_ID;
    }

    @Override
    public Field<Integer> field6() {
        return Staging.STAGING.IMPORT_ID;
    }

    @Override
    public Field<Integer> field7() {
        return Staging.STAGING.ELEMENT_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getData();
    }

    @Override
    public ElementType component3() {
        return getElementType();
    }

    @Override
    public String component4() {
        return getDesignation();
    }

    @Override
    public Integer component5() {
        return getParentId();
    }

    @Override
    public Integer component6() {
        return getImportId();
    }

    @Override
    public Integer component7() {
        return getElementId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getData();
    }

    @Override
    public ElementType value3() {
        return getElementType();
    }

    @Override
    public String value4() {
        return getDesignation();
    }

    @Override
    public Integer value5() {
        return getParentId();
    }

    @Override
    public Integer value6() {
        return getImportId();
    }

    @Override
    public Integer value7() {
        return getElementId();
    }

    @Override
    public StagingRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public StagingRecord value2(String value) {
        setData(value);
        return this;
    }

    @Override
    public StagingRecord value3(ElementType value) {
        setElementType(value);
        return this;
    }

    @Override
    public StagingRecord value4(String value) {
        setDesignation(value);
        return this;
    }

    @Override
    public StagingRecord value5(Integer value) {
        setParentId(value);
        return this;
    }

    @Override
    public StagingRecord value6(Integer value) {
        setImportId(value);
        return this;
    }

    @Override
    public StagingRecord value7(Integer value) {
        setElementId(value);
        return this;
    }

    @Override
    public StagingRecord values(Integer value1, String value2, ElementType value3, String value4, Integer value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StagingRecord
     */
    public StagingRecord() {
        super(Staging.STAGING);
    }

    /**
     * Create a detached, initialised StagingRecord
     */
    public StagingRecord(Integer id, String data, ElementType elementType, String designation, Integer parentId, Integer importId, Integer elementId) {
        super(Staging.STAGING);

        set(0, id);
        set(1, data);
        set(2, elementType);
        set(3, designation);
        set(4, parentId);
        set(5, importId);
        set(6, elementId);
    }
}
